name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Build x86 Linux
      run: GOOS=linux GOARCH=386 go build -ldflags "-s -w" -v -o build/http-linux-x86 .

    - name: Build x86 Windows
      run: GOOS=windows GOARCH=386 go build -ldflags "-s -w" -v -o build/http-windows-x86.exe .
    
    - name: Build arm Linux
      run: GOOS=linux GOARCH=arm go build -ldflags "-s -w" -v -o build/http-linux-arm .
    
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: release
        # Directory containing files to upload
        path: build/
